# Generated by Django 2.1.5 on 2020-03-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.AlterField(
            model_name='posts',
            name='type',
            field=models.CharField(blank=True, choices=[('Notice', 'Notice'), ('Announcement', 'Announce'), ('other', 'Other')], max_length=10),
        ),
    ]
